config/routes.rb
Rails.application.routes.draw do
  # get  'home' => 'home#index'
  # root 'home#index'

  resources :users, only: [:index], path: '/' do
    collection do
      get 'mypage'
      get 'login'
      get 'logout'
    end
  end

  namespace :my_page do
    resources :watch_list, only: [:index,  :create, :destroy]
    resources :cart, only: [:index, :create, :destroy]
    resources :selling_items, only: [:index]
  end

  namespace :marketplaces do
    resources :guitars, only: [:index]
    resources :basses, only: [:index]
    resources :keyboards, only: [:index]
  end

  resources :sell_items do
    collection do
     #get 'get_categories'
     #get 'get_product_models'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :sell_item
  validates :user_id, :uniqueness => {:scope => :sell_item_id}
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :instrument
end

app/models/condition.rb
class Condition < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :picture, PictureUploader
  belongs_to :sell_item
  validate :picture_size

  private
    def picture_size
      if picture.size > 5.megabytes
        erros.add(:picture, "5メガバイト以下のファイルを送信してください")
      end
    end
end

app/models/instrument.rb
class Instrument < ApplicationRecord
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :instrument
  belongs_to :brand
end

app/models/sell_item.rb
class SellItem < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :user
  belongs_to :instrument
  belongs_to :brand
  belongs_to :condition
  has_many :images, dependent: :destroy, inverse_of: :sell_item
  accepts_nested_attributes_for :images, allow_destroy: true
  validates :user_id, presence: true
  validates :instrument_id, presence: true
  validates :category_id, presence: true
  validates :brand_id, presence: true
  validates :product_model_id, presence: true
  validates :condition_id, presence: true
  validates :name, presence: true, length: { maximum: 140 }
  validates :listing_title, presence: true, length: { maximum: 140 }
  validates :price, numericality: { greater_than_or_equal_to: 1,  only_integer: true }

  # sellItem.errors.messages => {:price=>["must be greater than or equal to 0"]}
  # sellItem.errors.full_messages => ["Price must be greater than or equal to 0"]
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sell_items
  has_many :carts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/my_page/cart_controller.rb
class MyPage::CartController < ApplicationController
  def index
    @carts = []
    User.first.carts.each do |cart|
      @carts.append(SellItem.find_by(id: cart.sell_item_id))
    end
  end

  def create
    cart = Cart.new(user_id: User.first.id, sell_item_id: params[:sell_item_id])
    if cart.save
      redirect_to my_page_cart_index_url
    else
      redirect_to my_page_cart_index_url
    end
  end

  def destroy
    User.first.carts.find_by(sell_item_id: params[:id]).destroy
    redirect_to my_page_cart_index_url
  end

  #private
  #def cart_params
  #  params.require(:sell_item).permit(:sell_item_id,)
  #end
end

app/controllers/sell_items_controller.rb
class SellItemsController < ApplicationController
  def index
    @sell_items = SellItem.all
    # binding.pry
  end

  def show
    @sell_item = SellItem.find_by(id: params[:id])
  end

  def new
    gon.categories = {}
    Category.all.each do |c|
      if !gon.categories.has_key?(c.instrument_id)
        gon.categories[c.instrument_id] = {}
        gon.categories[c.instrument_id][c.id] = c.name
      else
        gon.categories[c.instrument_id][c.id] = c.name
      end
    end

    gon.models = {}
    ProductModel.all.each do |p|
      if !gon.models.has_key?(p.instrument_id)
        gon.models[p.instrument_id] = {}
        if gon.models[p.instrument_id].empty?
          gon.models[p.instrument_id][p.brand_id] = {}
          gon.models[p.instrument_id][p.brand_id][p.id] = p.name
        else
          if !gon.models[p.instrument_id][p.brand_id].has_key?(p.id)
            gon.models[p.instrument_id][p.brand_id][p.id] = p.name
          else
            gon.models[p.instrument_id][p.brand_id][p.id] = p.name
          end
        end
      else
        if !gon.models[p.instrument_id].has_key?(p.brand_id)
          gon.models[p.instrument_id][p.brand_id] = {}
          gon.models[p.instrument_id][p.brand_id][p.id] = p.name
        else
          gon.models[p.instrument_id][p.brand_id][p.id] = p.name
        end
      end
    end
    @sell_item = User.first.sell_items.build
    @sell_item.images.build
  end

  def create
    # @sell_item = current_user.sell_items.build
    @sell_item = User.first.sell_items.build(sell_item_params)
    if @sell_item.save
      # redirect_to new_sell_item_url
      redirect_to sell_items_url
    else
      # render "new"
      render new_sell_item_path
    end
  end

  def edit
  end

  private
  def sell_item_params
    params.require(:sell_item).permit(
        :instrument_id,
        :category_id,
        :brand_id,
        :product_model_id,
        :condition_id,
        :name,
        :price,
        :listing_title,
        images_attributes: [:id, :picture, :_destroy]
    )
  end


  # def get_categories
  #  @categories = Category.where(instrument_id: params[:category_id])
  #  respond_to do |format|
  #    format.js
  #  end
  #   @sell_item = User.first.sell_items.build
  #   render partial: 'select_category', locals: {instrument_id: params[:instrument_id]}
  # end

  # def get_product_models
  #  render partial: 'select_city', locals: {prefecture_id: params[:prefecture_id]}
  # end

  # images_attributes
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @sell_items = SellItem.all # take(20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/marketplaces/basses_helper.rb
module Marketplaces::BassesHelper
end

app/helpers/marketplaces/guitars_helper.rb
module Marketplaces::GuitarsHelper
end

app/helpers/my_page/cart_helper.rb
module MyPage::CartHelper
end

app/helpers/my_page/selling_items_helper.rb
module MyPage::SellingItemsHelper
end

app/helpers/my_page/watch_list_helper.rb
module MyPage::WatchListHelper
end

app/helpers/sell_items_helper.rb
module SellItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/sell_items/_image_fields.html.erb
<div class="nested-fields col-sm-3 dropzone" id="dropzone">
  <%= f.label :picture, id: "file-wrapper", class: "file-wrapper"%>
  <%= f.file_field :picture, id: "file", style: "display:none;" %>
  <%= link_to_remove_association "削除する", f, class:"btn btn-success", id: "remove-btn"%>
</div>

app/views/sell_items/_select_category.html.erb
<%= f.label :category_id %>
<%= f.collection_select :category_id, Category.where(instrument_id: instrument_id), :id, :name, {}, class: 'form-control'%>

app/views/sell_items/_select_product_model.html.erb
<%= f.label :product_model_id %>
<%= f.collection_select :product_model_id, ProductModel.where(instrument_id: instrument_id, brand_id: brand_id), :id, :name, {}, class: 'form-control' %>

app/views/sell_items/index.html.erb
<%= stylesheet_link_tag "custom/items", :media => "all" %>
<h1 class="text-center">商品一覧</h1>
<%= render partial: "layouts/items", locals: {items: @sell_items} %>

app/views/sell_items/new.html.erb
<%= stylesheet_link_tag "custom/sell_item", :media => "all" %>
<%= javascript_include_tag "custom/sell_items.js" %>

<%= form_for(@sell_item, html:{multipart: true}) do |f| %>
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="col-sm-8 col-sm-offset-2">
      <%= f.label :listing_title %>
      <%= f.text_field :listing_title, class: 'form-control' %>
    </div>

    <div class="col-sm-4 col-sm-offset-2">
        <%= f.label :insturment_id %>
        <%= f.collection_select :instrument_id, Instrument.all, :id, :name, {}, class: 'form-control' %>
    </div>

    <div class="category-area col-sm-4">
      <%= f.label :category_id %>
      <%= f.collection_select :category_id, Category.where(instrument_id: Instrument.first.id), :id, :name, {}, class: 'form-control'%>
    </div>

    <div class="col-sm-4 col-sm-offset-2">
        <%= f.label :brand_id %>
        <%= f.collection_select :brand_id, Brand.all, :id, :name, {}, class: 'form-control' %>
    </div>

    <div class="product-model-area col-sm-4">
      <%= render partial: 'select_product_model', locals: {instrument_id: Instrument.first.id, brand_id: Brand.second.id, f: f} %>
    </div>

    <div class="col-sm-4 col-sm-offset-2">
      <%= f.label :condition_id %>
      <%= f.collection_select :condition_id, Condition.all, :id, :name, {}, class: 'form-control' %>
    </div>

    <div class="col-sm-4">
      <%= f.label :price %>
      <%= f.number_field :price, class: 'form-control' %>
    </div>

    <div class="col-sm-8 col-sm-offset-2">
      <div id="dropzoneWrapper" class="dropzoneWrapper">
        <%= f.label :images, id: "images-label" %>
        <div id="dropzoneWrapperInside" class="row">
          <%= f.fields_for :images do | image | %>
              <%= render 'image_fields', f: image %>
              <div id="add-picture-btn-wrapper" class="col-sm-12 text-right">
                <%= link_to_add_association '写真追加', f, :images, class: "btn btn-primary", id: "add-picture-btn" %>
              </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-sm-offset-8 col-sm-2">
      <%= f.submit "Submit", class: 'form-control'%>
    </div>
  </div>
<% end %>

app/views/sell_items/show.html.erb
<%= stylesheet_link_tag "custom/item", :media => "all" %>
<div class="item-detail-wrapper">
  <div class="item-detail-main-wrapper">
    <h2 class="item-detail-main-title"><%= @sell_item.listing_title %></h2>
    <img src="<%= @sell_item.images[0].picture.url%>" alt="" class="item-detail-main-logo">
    <p class="item-detail-main-info">ブランド: <%= Brand.find_by(id: @sell_item.brand_id).name %></p>
    <p class="item-detail-main-info">カテゴリ: <%= Category.find_by(id: @sell_item.category_id).name %></p>
    <p class="item-detail-main-info">状態: <%= Condition.find_by(id: @sell_item.condition_id).name %></p>
  </div>
  <div class="item-detail-sub-wrapper">
    <p class="item-price"><%= @sell_item.price.to_s(:delimited, delimiter: ',') %>円</p>
    <a href="#" class="btn btn-success item-detail-btn">ウォッチリストに入れる</a>
    <%= link_to "カートに入れる", my_page_cart_index_path(sell_item_id: @sell_item.id), method: :post, class: "btn btn-primary item-detail-btn" %>
  </div>
</div>

app/views/users/index.html.erb
<%= stylesheet_link_tag "custom/index", :media => "all" %>
<div id="intro-wrapper">
    <a href="#"><img src="/guitar.jpg" alt="Intro" id="intro-picture"></a>
</div>
<div id="wrapper" class="container-fluid">
  <div class="row">
    <div class="main-wrapper container">
    <!-- intro -->
    <!-- intro_end -->

    <!-- main -->
      <div class="main col-sm-12 col-xs-12">
        <h2 class="text-center">新着アイテム</h2>
        <div class="container-fluid">
            <div class="row">
              <% @sell_items.each do | item |%>
                <div class="col-xs-4 col-md-3 item-wrapper">
                  <div class="picture-wrapper">
                    <%= link_to item do %>
                      <%= image_tag item.images[0].picture.url, class: "picture" %>
                    <% end %>
                  </div>
                  <div class="item-infomation">
                    <small class="listing-title">
                      <%= item.listing_title.truncate(20) %>
                    </small><br>
                    <span class="price">
                      <%= item.price.to_s(:delimited, delimiter: ',') %>円
                    </span>
                  </div>
                </div>
              <% end %>
            </div>
            <%= link_to "もっと見る", sell_items_path, class: "btn btn-warning see-more-btn"%>
        </div>
      </div>
    <!-- main_end -->
    </div>
  </div>
</div>