config/routes.rb
Rails.application.routes.draw do
  # get  'home' => 'home#index'
  # root 'home#index'

  resources :users, only: [:index], path: '/' do
    collection do
      get 'mypage'
      get 'login'
      get 'logout'
    end
  end

  namespace :my_page do
    resources :watch_list, only: [:index,  :create, :destroy]
    resources :cart, only: [:index, :create, :destroy]
    resources :selling_items, only: [:index]
  end

  namespace :marketplaces do
    resources :guitars, only: [:index]
    resources :basses, only: [:index]
    resources :keyboards, only: [:index]
  end

  resources :sell_items do
    collection do
     #get 'get_categories'
     #get 'get_product_models'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :sell_item
  validates :user_id, :uniqueness => {:scope => :sell_item_id}
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :instrument
end

app/models/condition.rb
class Condition < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :picture, PictureUploader
  belongs_to :sell_item
  validate :picture_size

  private
    def picture_size
      if picture.size > 5.megabytes
        erros.add(:picture, "5メガバイト以下のファイルを送信してください")
      end
    end
end

app/models/instrument.rb
class Instrument < ApplicationRecord
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :instrument
  belongs_to :brand
end

app/models/sell_item.rb
class SellItem < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :user
  belongs_to :instrument
  belongs_to :brand
  belongs_to :condition
  has_many :images, dependent: :destroy, inverse_of: :sell_item
  accepts_nested_attributes_for :images, allow_destroy: true
  validates :user_id, presence: true
  validates :instrument_id, presence: true
  validates :category_id, presence: true
  validates :brand_id, presence: true
  validates :product_model_id, presence: true
  validates :condition_id, presence: true
  validates :name, presence: true, length: { maximum: 140 }
  validates :listing_title, presence: true, length: { maximum: 140 }
  validates :price, numericality: { greater_than_or_equal_to: 1,  only_integer: true }

  # sellItem.errors.messages => {:price=>["must be greater than or equal to 0"]}
  # sellItem.errors.full_messages => ["Price must be greater than or equal to 0"]
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sell_items
  has_many :carts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sell_items_controller.rb
class SellItemsController < ApplicationController
  def index
    @sell_items = SellItem.all
    # binding.pry
  end

  def show
    @sell_item = SellItem.find_by(id: params[:id])
  end

  def new
    gon.categories = {}
    Category.all.each do |c|
      if !gon.categories.has_key?(c.instrument_id)
        gon.categories[c.instrument_id] = {}
        gon.categories[c.instrument_id][c.id] = c.name
      else
        gon.categories[c.instrument_id][c.id] = c.name
      end
    end

    gon.models = {}
    ProductModel.all.each do |p|
      if !gon.models.has_key?(p.instrument_id)
        gon.models[p.instrument_id] = {}
        if gon.models[p.instrument_id].empty?
          gon.models[p.instrument_id][p.brand_id] = {}
          gon.models[p.instrument_id][p.brand_id][p.id] = p.name
        else
          if !gon.models[p.instrument_id][p.brand_id].has_key?(p.id)
            gon.models[p.instrument_id][p.brand_id][p.id] = p.name
          else
            gon.models[p.instrument_id][p.brand_id][p.id] = p.name
          end
        end
      else
        if !gon.models[p.instrument_id].has_key?(p.brand_id)
          gon.models[p.instrument_id][p.brand_id] = {}
          gon.models[p.instrument_id][p.brand_id][p.id] = p.name
        else
          gon.models[p.instrument_id][p.brand_id][p.id] = p.name
        end
      end
    end
    @sell_item = User.first.sell_items.build
    @sell_item.images.build
  end

  def create
    # @sell_item = current_user.sell_items.build
    @sell_item = User.first.sell_items.build(sell_item_params)
    if @sell_item.save
      # redirect_to new_sell_item_url
      redirect_to sell_items_url
    else
      # render "new"
      render new_sell_item_path
    end
  end

  def edit
  end

  private
  def sell_item_params
    params.require(:sell_item).permit(
        :instrument_id,
        :category_id,
        :brand_id,
        :product_model_id,
        :condition_id,
        :name,
        :price,
        :listing_title,
        images_attributes: [:id, :picture, :_destroy]
    )
  end


  # def get_categories
  #  @categories = Category.where(instrument_id: params[:category_id])
  #  respond_to do |format|
  #    format.js
  #  end
  #   @sell_item = User.first.sell_items.build
  #   render partial: 'select_category', locals: {instrument_id: params[:instrument_id]}
  # end

  # def get_product_models
  #  render partial: 'select_city', locals: {prefecture_id: params[:prefecture_id]}
  # end

  # images_attributes
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @sell_items = SellItem.all # take(20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/marketplaces/basses_helper.rb
module Marketplaces::BassesHelper
end

app/helpers/my_page/cart_helper.rb
module MyPage::CartHelper
end

app/helpers/my_page/watch_list_helper.rb
module MyPage::WatchListHelper
end

app/helpers/sell_items_helper.rb
module SellItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">footer</div>

app/views/layouts/_header.html.erb
<header>
  <div class="header-logo-wrapper">
    <%= link_to "Resona", "/", class: "header-logo-link" %>
  </div>
  <div class="header-main-wrapper">
    <input type="text" class="header-search-form form-control" placeholder="Fender Guitar">
    <div class="header-main-items-wrapper">
      <div class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">カテゴリー<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "ギター", marketplaces_guitars_path %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "ベース", marketplaces_basses_path %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "キーボード", marketplaces_keyboards_path %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="header-sub-wrapper">
    <ul class="header-sub-items-wrapper">
      <li class="header-sub-item"><%= link_to "売る", new_sell_item_path %></li>
      <li class="header-sub-item"><a href="#">カート</a></li>
      <li class="header-sub-item"><%= link_to "マイページ", my_page_selling_items_path %></li>
      <li class="header-sub-item"><a href="#">ログアウト</a></li>
    </ul>
  </div>
</header>

app/views/layouts/_items.html.erb
<div id="items-index-wrapper" class="container-fluid">
  <div class="row">
    <div id="items-index-contents-wrapper" class="container">
      <!-- side -->
      <div id="side-wrapper" class="col-sm-3 hidden-xs">
      </div>
      <!-- main -->
      <div id="main-wrapper" class="col-sm-9 col-xs-12">
        <div class="container-fluid">
          <div class="row">
            <% items.each do |item| %>
              <a href="#" class="item-link-wrapper">
                <div class="item-wrapper col-xs-6 col-sm-4 col-md-3">
                  <div class="item-contents">
                    <div class="picture-wrapper">
                      <%= image_tag item.images[0].picture.url, class: "picture" %>
                    </div>
                    <div class="item-infomation">
                      <p>
                        <small class="listing-title">
                          <%= item.listing_title.truncate(20) %>
                        </small><br>
                        <span class="price">
                          <%= item.price.to_s(:delimited, delimiter: ',') %>円
                        </span>
                      </p>
                    </div>
                  </div>
                </div>
              </a>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_mypage.html.erb
<div class="mypage-list-wrapper">
  <div class="mypage-link-list-wrapper">
    <%= link_to "売り物", my_page_selling_items_path, class: "mypage-link mypage-sell-link" %>
    <%= link_to "ウォッチ", my_page_watch_list_index_path, class: "mypage-link mypage-watch-link" %>
    <%= link_to "カート", my_page_cart_index_path, class: "mypage-link mypage-cart-link" %>
  </div>
  <div class="mypage-item-list-wrapper">
    <% items.each do |item| %>
    <div class="mypage-item-wrapper">
      <%= image_tag item.images[0].picture.url, class: "mypage-item mypage-item-logo"%>
      <p class="mypage-item mypage-item-title"><%= item.listing_title %></p>
      <p class="mypage-item mypage-item-price"><%= item.price.to_s(:delimited, delimiter: ',')%>円</p>
      <a href="#" class="mypage-item mypage-item-btn btn btn-warning">編集する</a>
      <a href="#" class="mypage-item mypage-item-btn btn btn-danger">削除する</a>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Resona</title>
    <%= csrf_meta_tags %>
    <%= include_gon %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='<%= "#{controller.controller_name}" %>'>
    <!-- Header -->
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>